"""
Auto-generated schema template from Neo4j database.

Generated by: backend/db/generate_schema_template.py
Last updated: 2026-01-05 15:31:17

DO NOT EDIT THIS FILE MANUALLY!
Run `python backend/db/generate_schema_template.py` to regenerate.
"""

import json

# Human-readable schema description for LLM prompts
SCHEMA_TEXT = """\
Nodes:
- (:Building {HAS_FUNCTION (STRING NOT NULL), IN_DISTRICT (STRING NOT NULL), area (STRING NOT NULL), centroid (STRING NOT NULL), floors_above (INTEGER NOT NULL), floors_below (INTEGER NOT NULL), geometry_geojson (STRING NOT NULL), id (STRING NOT NULL), name (STRING NOT NULL), post_code (STRING NOT NULL), street_name (STRING NOT NULL)}) - 96,572 nodes
- (:District {Gemeinde_name (STRING NOT NULL), Gemeinde_schluessel (STRING NOT NULL), Land_name (STRING NOT NULL), Land_schluessel (STRING NOT NULL), Schluessel_gesamt (STRING NOT NULL), WKT (STRING NOT NULL), centroid (STRING NOT NULL), gml_id (STRING NOT NULL)}) - 12 nodes
- (:Function {code (STRING NOT NULL), description (STRING NOT NULL)}) - 234 nodes

Relationships:
- (Building)-[:HAS_FUNCTION]->(Function) - 96,572 instances
- (Building)-[:IN_DISTRICT]->(District) - 96,572 instances
"""

# Structured schema as dictionary
SCHEMA_DICT = {
    "nodes": {
        "Building": {
            "properties": {
                "HAS_FUNCTION": "STRING NOT NULL",
                "IN_DISTRICT": "STRING NOT NULL",
                "area": "STRING NOT NULL",
                "centroid": "STRING NOT NULL",
                "floors_above": "INTEGER NOT NULL",
                "floors_below": "INTEGER NOT NULL",
                "geometry_geojson": "STRING NOT NULL",
                "id": "STRING NOT NULL",
                "name": "STRING NOT NULL",
                "post_code": "STRING NOT NULL",
                "street_name": "STRING NOT NULL"
            },
            "count": 96572
        },
        "District": {
            "properties": {
                "Gemeinde_name": "STRING NOT NULL",
                "Gemeinde_schluessel": "STRING NOT NULL",
                "Land_name": "STRING NOT NULL",
                "Land_schluessel": "STRING NOT NULL",
                "Schluessel_gesamt": "STRING NOT NULL",
                "WKT": "STRING NOT NULL",
                "centroid": "STRING NOT NULL",
                "gml_id": "STRING NOT NULL"
            },
            "count": 12
        },
        "Function": {
            "properties": {
                "code": "STRING NOT NULL",
                "description": "STRING NOT NULL"
            },
            "count": 234
        }
    },
    "relationships": [
        {
            "type": "HAS_FUNCTION",
            "source": "Building",
            "target": "Function",
            "count": 96572
        },
        {
            "type": "IN_DISTRICT",
            "source": "Building",
            "target": "District",
            "count": 96572
        }
    ]
}

# Important hints for Cypher query generation
SCHEMA_HINTS = [
    "ACHTUNG: Function.code ist STRING! Nutze ['1010', '2020'] mit Quotes!",
    "Building.centroid: Parse String und konvertiere zu Point für Distanzberechnungen. Achte darauf, dass der WKT-String ETRS89 Koordinaten nutzt!",
    "District.centroid: Achte darauf, dass der WKT-String WGS84 Koordinaten nutzt!",
    "Building hat Properties UND Relationships - nutze Relationships für Joins!",
    "Verwende immer MATCH statt OPTIONAL MATCH wenn möglich.",
    "Beachte, dass viele Attribute (z.B. house_number) Null-Werte enthalten können. Filter diese immer heraus. Außerdem enthalten Hausnummern manchmal Buchstaben (z.B. '12a'), berücksichtige dies bei numerischen Filtern.",
    "Solltest du Felder sortieren wollen, nutze ORDER BY sollten mögliche Null-Werte bereits durch WHERE gefiltert worden sein, da diese ansonsten bei DESC ganz oben stehen.",
    "Gib alle relevanten Properties zurück, die Geometrie aller berücksichtigten Gebäude muss allerdings immer enthalten sein."
]


def get_schema_for_prompt() -> str:
    """
    Get formatted schema text for inclusion in LLM prompts.
    
    Returns:
        Formatted schema description with nodes, relationships, and hints.
    """
    parts = [SCHEMA_TEXT]
    
    if SCHEMA_HINTS:
        parts.append("\nWichtige Hinweise:")
        for hint in SCHEMA_HINTS:
            parts.append(f"- {hint}")
    
    return "\n".join(parts)


def get_schema_dict() -> dict:
    """
    Get structured schema as dictionary.
    
    Returns:
        Dictionary with 'nodes' and 'relationships' keys.
    """
    return SCHEMA_DICT
