"""
Auto-generated schema template from Neo4j database.

Generated by: backend/db/generate_schema_template.py
Last updated: 2026-01-10 16:43:51

DO NOT EDIT THIS FILE MANUALLY!
Run `python backend/db/generate_schema_template.py` to regenerate.
"""

# Human-readable schema description for LLM prompts
SCHEMA_TEXT = """\
Nodes:
- (:Building {area (STRING NOT NULL), centroid (STRING NOT NULL), floors_above (INTEGER NOT NULL), floors_below (INTEGER NOT NULL), geometry_geojson (STRING NOT NULL), house_number (STRING NOT NULL), id (STRING NOT NULL), name (STRING NOT NULL), post_code (STRING NOT NULL), street_name (STRING NOT NULL)}) - 96,572 nodes
- (:District {Gemeinde_name (STRING NOT NULL), Gemeinde_schluessel (STRING NOT NULL), Land_name (STRING NOT NULL), Land_schluessel (STRING NOT NULL), Schluessel_gesamt (STRING NOT NULL), centroid (STRING NOT NULL), geometry_geojson (STRING NOT NULL), gml_id (STRING NOT NULL)}) - 3 nodes
- (:Function {code (INTEGER NOT NULL), description (STRING NOT NULL), description_embedding_large (LIST<FLOAT NOT NULL> NOT NULL), description_embedding_small (LIST<FLOAT NOT NULL> NOT NULL), name (STRING NOT NULL)}) - 234 nodes

Relationships:
- (Building)-[:HAS_FUNCTION]->(Function) - 96,572 instances
- (Function)-[:HAS_SUBFUNCTION]->(Function) - 223 instances
- (Building)-[:IN_DISTRICT]->(District) - 96,683 instances
"""

# Structured schema as dictionary
SCHEMA_DICT = {
    "nodes": {
        "Building": {
            "properties": {
                "area": "STRING NOT NULL",
                "centroid": "STRING NOT NULL",
                "floors_above": "INTEGER NOT NULL",
                "floors_below": "INTEGER NOT NULL",
                "geometry_geojson": "STRING NOT NULL",
                "house_number": "STRING NOT NULL",
                "id": "STRING NOT NULL",
                "name": "STRING NOT NULL",
                "post_code": "STRING NOT NULL",
                "street_name": "STRING NOT NULL"
            },
            "count": 96572
        },
        "District": {
            "properties": {
                "Gemeinde_name": "STRING NOT NULL",
                "Gemeinde_schluessel": "STRING NOT NULL",
                "Land_name": "STRING NOT NULL",
                "Land_schluessel": "STRING NOT NULL",
                "Schluessel_gesamt": "STRING NOT NULL",
                "centroid": "STRING NOT NULL",
                "geometry_geojson": "STRING NOT NULL",
                "gml_id": "STRING NOT NULL"
            },
            "count": 3
        },
        "Function": {
            "properties": {
                "code": "INTEGER NOT NULL",
                "description": "STRING NOT NULL",
                "description_embedding_large": "LIST<FLOAT NOT NULL> NOT NULL",
                "description_embedding_small": "LIST<FLOAT NOT NULL> NOT NULL",
                "name": "STRING NOT NULL"
            },
            "count": 234
        }
    },
    "relationships": [
        {
            "type": "HAS_FUNCTION",
            "source": "Building",
            "target": "Function",
            "count": 96572
        },
        {
            "type": "HAS_SUBFUNCTION",
            "source": "Function",
            "target": "Function",
            "count": 223
        },
        {
            "type": "IN_DISTRICT",
            "source": "Building",
            "target": "District",
            "count": 96683
        }
    ]
}

# Important hints for Cypher query generation
SCHEMA_HINTS = [
    "WICHTIG: Function.code ist INTEGER! Nutze [1010, 2020] NICHT ['1010', '2020']!",
    "District.centroid: Achte darauf, dass der WKT-String WGS84 Koordinaten nutzt!",
    "Verwende immer MATCH statt OPTIONAL MATCH wenn möglich.",
    "Versuche immer deine Cyper-Queries so zu schreiben, dass du erst über MATCH die relevanten Knoten filterst, dann über WHERE weitere Bedingungen anwendest, und am Ende alle relevanten Gebäude mit collect(b) AS buildings zurückgibst."
]


def get_schema_for_prompt() -> str:
    """
    Get formatted schema text for inclusion in LLM prompts.
    
    Returns:
        Formatted schema description with nodes, relationships, and hints.
    """
    parts = [SCHEMA_TEXT]
    
    if SCHEMA_HINTS:
        parts.append("\nWichtige Hinweise:")
        for hint in SCHEMA_HINTS:
            parts.append(f"- {hint}")
    
    return "\n".join(parts)


def get_schema_dict() -> dict:
    """
    Get structured schema as dictionary.
    
    Returns:
        Dictionary with 'nodes' and 'relationships' keys.
    """
    return SCHEMA_DICT
